# https://github.com/Zeronetsec/Ares

function lib::shell::libso::init() {
    set -o errexit

    enable -f \
        "${__lib__}/shell/libso/loadso.so" \
        loadso || \
        return 1

    builtin loadso : '(
        lib/shell/libso/destroyf -> destroyf
        lib/shell/libso/destroyso -> destroyso
        lib/shell/libso/destroyv -> destroyv
        lib/shell/libso/include -> include
        lib/shell/libso/loadso -> loadso
        lib/shell/libso/rhome -> rhome
        lib/shell/libso/dynav -> dynav
        lib/shell/libso/dynap -> dynap
        lib/shell/libso/shmod -> shmod
        lib/shell/libso/catchypr -> catchypr
        lib/shell/libso/unreadonlyf -> unreadonlyf
        lib/shell/libso/unreadonlyv -> unreadonlyv
        lib/shell/libso/error -> error
        lib/shell/libso/llsi -> llsi
        lib/shell/libso/loadrc -> loadrc
    )' || return 1

    trap 'builtin error' ERR
}; readonly -f lib::shell::libso::init; export -f lib::shell::libso::init

# Copyright (c) 2026 Zeronetsec